/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kickassdb;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Otto
 */
public class KickAssTable extends javax.swing.JPanel {

    /**
     * Creates new form KickAssTable
     */
    public KickAssTable() {
        initComponents();
    }

    public void addTable(JTable table){

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelName = new javax.swing.JPanel();
        tableName = new javax.swing.JLabel();
        TableScrollPane = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        tableName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableName.setForeground(new java.awt.Color(0, 0, 102));
        tableName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tableName.setText("Name");

        javax.swing.GroupLayout panelNameLayout = new javax.swing.GroupLayout(panelName);
        panelName.setLayout(panelNameLayout);
        panelNameLayout.setHorizontalGroup(
            panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableName, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        panelNameLayout.setVerticalGroup(
            panelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNameLayout.createSequentialGroup()
                .addComponent(tableName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panelName);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableScrollPane.setViewportView(Table);

        add(TableScrollPane);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane TableScrollPane;
    private javax.swing.JPanel panelName;
    private javax.swing.JLabel tableName;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tableName
     */
    public javax.swing.JLabel getTableName() {
        return tableName;
    }

    /**
     * @param tableName the tableName to set
     */
    public void setTableName(javax.swing.JLabel tableName) {
        this.tableName = tableName;
    }

    /**
     * @return the Table
     */
    public javax.swing.JTable getTable() {
        return Table;
    }

    /**
     * @param Table the Table to set
     */
    public void setTable(javax.swing.JTable t) {
        this.Table = t;
    }

}
