/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

package kickassdb;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>src/kickassdb/lexer.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\3\1\52\1\3\1\3\22\0\1\4\1\5\1\23"+
    "\5\0\1\16\1\17\1\15\1\13\1\22\1\14\1\20\1\10\12\2"+
    "\1\6\1\21\1\11\1\7\1\12\1\5\1\0\1\47\1\42\1\27"+
    "\1\31\1\30\1\33\1\43\1\44\1\37\2\1\1\45\1\1\1\34"+
    "\1\26\1\24\1\1\1\25\1\41\1\35\1\32\1\1\1\46\1\50"+
    "\1\51\5\1\1\1\1\1\1\47\1\42\1\27\1\31\1\30\1\33"+
    "\1\43\1\44\1\37\2\1\1\45\1\1\1\34\1\26\1\24\1\1"+
    "\1\25\1\41\1\35\1\32\1\1\1\46\1\50\1\51\1\1\12\0"+
    "\1\52\252\0\2\36\115\0\1\40\u1ea8\0\1\52\1\52\udfd6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\2\6\2\10\1\7\1\11\1\12\1\1\1\13\1\14"+
    "\1\1\6\2\1\1\7\2\1\15\1\2\2\0\1\16"+
    "\1\17\1\0\1\20\1\0\1\21\4\2\1\22\1\2"+
    "\1\23\11\2\1\24\1\25\1\26\1\24\1\25\1\26"+
    "\10\2\1\0\1\3\1\4\1\2\1\27\2\2\1\30"+
    "\1\31\1\0\1\2\1\0\1\2\1\32\5\2\1\0"+
    "\3\2\1\33\2\2\1\0\2\2\1\34\1\35\3\2"+
    "\1\36\1\0\1\36\1\2\2\37\2\2\1\0\1\2"+
    "\1\40\1\41\1\0\2\2\1\0\1\2\1\42\1\43"+
    "\1\0\4\2\1\44\2\45\1\2\1\46\2\47\1\0"+
    "\2\2\2\50\2\51\1\52\1\2\1\53\1\0\1\2"+
    "\1\0\3\2\1\0\1\2\2\54\1\55\1\2\2\56"+
    "\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\53\0\254\0\53\0\327"+
    "\0\u0102\0\327\0\53\0\u012d\0\53\0\53\0\53\0\u0158"+
    "\0\53\0\53\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a"+
    "\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c\0\u0387\0\u03b2"+
    "\0\u03dd\0\53\0\u0408\0\u0433\0\u045e\0\53\0\53\0\u0489"+
    "\0\53\0\u0183\0\53\0\u04b4\0\u04df\0\u050a\0\u0535\0\126"+
    "\0\u0560\0\126\0\u058b\0\u05b6\0\u05e1\0\u060c\0\u0637\0\u0662"+
    "\0\u068d\0\u06b8\0\u06e3\0\53\0\u070e\0\53\0\126\0\u0739"+
    "\0\126\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u0810\0\u083b\0\u0866"+
    "\0\u0891\0\u08bc\0\u045e\0\u0489\0\u08e7\0\126\0\u0912\0\u093d"+
    "\0\126\0\126\0\u0968\0\u0993\0\u09be\0\u09e9\0\126\0\u0a14"+
    "\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0\0\u0aeb\0\u0b16\0\u0b41\0\u0b6c"+
    "\0\126\0\u0b97\0\u0bc2\0\u0bed\0\u0c18\0\u0c43\0\126\0\126"+
    "\0\u0c6e\0\u0c99\0\u0cc4\0\53\0\u0cef\0\126\0\u0d1a\0\53"+
    "\0\126\0\u0d45\0\u0d70\0\u0d9b\0\u0dc6\0\126\0\126\0\u0df1"+
    "\0\u0e1c\0\u0e47\0\u0e72\0\u0e9d\0\126\0\126\0\u0ec8\0\u0ef3"+
    "\0\u0f1e\0\u0f49\0\u0f74\0\126\0\53\0\126\0\u0f9f\0\126"+
    "\0\53\0\126\0\u0fca\0\u0ff5\0\u1020\0\53\0\126\0\53"+
    "\0\126\0\126\0\u104b\0\126\0\u1076\0\u10a1\0\u10cc\0\u10f7"+
    "\0\u1122\0\u114d\0\u1178\0\u11a3\0\53\0\126\0\126\0\u11ce"+
    "\0\53\0\126\0\126";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\5\1\2\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\3\1\27"+
    "\2\3\1\30\1\3\1\31\1\32\1\33\1\2\1\3"+
    "\1\34\1\35\1\3\1\36\1\37\1\40\1\41\1\3"+
    "\1\42\54\0\1\3\1\43\11\0\1\44\7\0\12\3"+
    "\1\0\1\3\1\0\11\3\3\0\1\4\15\0\1\45"+
    "\41\0\1\46\52\0\1\7\52\0\1\7\2\0\1\47"+
    "\42\0\1\4\11\0\1\50\56\0\1\51\33\0\5\52"+
    "\15\0\1\53\12\52\1\0\1\52\1\0\11\52\2\0"+
    "\1\3\1\43\11\0\1\44\7\0\1\3\1\54\4\3"+
    "\1\55\3\3\1\0\1\3\1\0\11\3\2\0\1\3"+
    "\1\43\11\0\1\44\7\0\4\3\1\56\5\3\1\0"+
    "\1\3\1\0\6\3\1\57\2\3\2\0\1\3\1\43"+
    "\11\0\1\44\7\0\1\3\1\60\4\3\1\61\1\62"+
    "\2\3\1\0\1\3\1\0\11\3\2\0\1\3\1\43"+
    "\11\0\1\44\7\0\10\3\1\63\1\3\1\0\1\3"+
    "\1\0\4\3\1\64\2\3\1\65\1\3\2\0\1\3"+
    "\1\43\11\0\1\44\7\0\2\3\1\66\3\3\1\67"+
    "\3\3\1\0\1\3\1\0\4\3\1\70\1\3\1\71"+
    "\2\3\2\0\1\3\1\43\11\0\1\44\7\0\1\3"+
    "\1\72\10\3\1\0\1\3\1\0\3\3\1\73\5\3"+
    "\34\0\1\74\1\75\3\0\2\76\12\0\1\3\1\43"+
    "\11\0\1\44\7\0\7\3\1\77\1\100\1\3\1\0"+
    "\1\3\1\76\1\101\10\3\2\0\1\3\1\43\11\0"+
    "\1\44\7\0\2\3\1\102\1\3\1\103\5\3\1\0"+
    "\1\3\1\0\11\3\2\0\1\3\1\43\11\0\1\44"+
    "\7\0\4\3\1\104\5\3\1\0\1\3\1\0\11\3"+
    "\2\0\1\3\1\43\11\0\1\44\7\0\2\3\1\105"+
    "\7\3\1\0\1\3\1\0\11\3\2\0\1\3\1\43"+
    "\11\0\1\44\7\0\12\3\1\0\1\3\1\0\3\3"+
    "\1\106\5\3\2\0\1\3\1\43\11\0\1\44\7\0"+
    "\1\3\1\107\6\3\1\110\1\3\1\0\1\3\1\0"+
    "\11\3\2\0\1\3\1\43\11\0\1\44\7\0\2\3"+
    "\1\111\7\3\1\0\1\3\1\0\11\3\2\0\1\3"+
    "\1\43\11\0\1\44\3\0\1\112\3\0\12\3\1\0"+
    "\1\3\1\0\11\3\3\0\1\43\52\0\1\113\51\0"+
    "\2\114\1\0\1\114\17\0\12\114\1\0\1\114\1\0"+
    "\11\114\2\0\1\3\1\43\11\0\1\44\7\0\2\3"+
    "\1\115\7\3\1\0\1\3\1\0\11\3\2\0\1\3"+
    "\1\43\11\0\1\44\7\0\11\3\1\116\1\0\1\3"+
    "\1\0\11\3\2\0\1\3\1\43\11\0\1\44\7\0"+
    "\11\3\1\117\1\0\1\3\1\0\11\3\2\0\1\3"+
    "\1\43\11\0\1\44\7\0\10\3\1\120\1\3\1\0"+
    "\1\3\1\0\11\3\2\0\1\3\1\43\11\0\1\44"+
    "\7\0\11\3\1\121\1\0\1\3\1\0\11\3\2\0"+
    "\1\3\1\43\11\0\1\44\7\0\5\3\1\122\4\3"+
    "\1\0\1\3\1\0\11\3\2\0\1\3\1\43\11\0"+
    "\1\44\7\0\12\3\1\0\1\3\1\123\1\124\10\3"+
    "\2\0\1\3\1\43\11\0\1\44\7\0\12\3\1\125"+
    "\1\126\1\0\11\3\2\0\1\3\1\43\11\0\1\44"+
    "\7\0\1\3\1\127\10\3\1\0\1\3\1\0\11\3"+
    "\2\0\1\3\1\43\11\0\1\44\7\0\10\3\1\130"+
    "\1\3\1\0\1\3\1\0\11\3\2\0\1\3\1\43"+
    "\11\0\1\44\7\0\2\3\1\131\7\3\1\0\1\3"+
    "\1\0\11\3\2\0\1\3\1\43\11\0\1\44\7\0"+
    "\12\3\1\0\1\3\1\0\4\3\1\132\4\3\2\0"+
    "\1\3\1\43\11\0\1\44\7\0\6\3\1\133\3\3"+
    "\1\0\1\3\1\0\11\3\2\0\1\3\1\43\11\0"+
    "\1\44\7\0\4\3\1\134\5\3\1\0\1\3\1\0"+
    "\11\3\36\0\1\135\16\0\1\3\1\43\11\0\1\44"+
    "\7\0\11\3\1\136\1\0\1\3\1\0\11\3\2\0"+
    "\1\3\1\43\11\0\1\44\7\0\2\3\1\137\7\3"+
    "\1\0\1\3\1\0\11\3\2\0\1\3\1\43\11\0"+
    "\1\44\7\0\12\3\1\0\1\3\1\0\2\3\1\140"+
    "\6\3\2\0\1\3\1\43\11\0\1\44\7\0\11\3"+
    "\1\141\1\0\1\3\1\0\11\3\2\0\1\3\1\43"+
    "\11\0\1\44\7\0\2\3\1\142\7\3\1\0\1\3"+
    "\1\0\11\3\2\0\1\3\1\43\11\0\1\44\7\0"+
    "\4\3\1\143\5\3\1\144\1\145\1\0\11\3\2\0"+
    "\1\3\1\43\11\0\1\44\7\0\1\3\1\146\10\3"+
    "\1\0\1\3\1\0\11\3\2\0\1\3\1\43\11\0"+
    "\1\44\7\0\5\3\1\147\4\3\1\0\1\3\1\0"+
    "\11\3\2\0\1\3\1\43\11\0\1\44\7\0\1\3"+
    "\1\150\10\3\1\0\1\3\1\0\11\3\3\0\1\3"+
    "\51\0\1\3\1\43\11\0\1\44\7\0\3\3\1\151"+
    "\6\3\1\0\1\3\1\0\11\3\2\0\1\3\1\43"+
    "\11\0\1\44\7\0\6\3\1\152\3\3\1\0\1\3"+
    "\1\0\11\3\2\0\1\3\1\43\11\0\1\44\7\0"+
    "\12\3\1\0\1\3\1\0\2\3\1\153\6\3\31\0"+
    "\1\154\5\0\2\155\14\0\1\3\1\43\11\0\1\44"+
    "\7\0\4\3\1\156\5\3\1\155\1\157\1\0\11\3"+
    "\36\0\1\160\16\0\1\3\1\43\11\0\1\44\7\0"+
    "\11\3\1\161\1\0\1\3\1\0\11\3\2\0\1\3"+
    "\1\43\11\0\1\44\7\0\3\3\1\162\6\3\1\0"+
    "\1\3\1\0\11\3\2\0\1\3\1\43\11\0\1\44"+
    "\7\0\12\3\1\0\1\3\1\0\6\3\1\163\2\3"+
    "\2\0\1\3\1\43\11\0\1\44\7\0\12\3\1\0"+
    "\1\3\1\164\1\165\10\3\2\0\1\3\1\43\11\0"+
    "\1\44\7\0\4\3\1\166\5\3\1\0\1\3\1\0"+
    "\11\3\2\0\1\3\1\43\11\0\1\44\7\0\10\3"+
    "\1\167\1\3\1\0\1\3\1\0\11\3\31\0\1\170"+
    "\23\0\1\3\1\43\11\0\1\44\7\0\4\3\1\171"+
    "\5\3\1\0\1\3\1\0\11\3\2\0\1\3\1\43"+
    "\11\0\1\44\7\0\12\3\1\0\1\3\1\0\4\3"+
    "\1\172\4\3\2\0\1\3\1\43\11\0\1\44\7\0"+
    "\12\3\1\173\1\174\1\0\11\3\2\0\1\3\1\43"+
    "\11\0\1\44\7\0\1\175\11\3\1\0\1\3\1\0"+
    "\11\3\2\0\1\3\1\43\11\0\1\44\7\0\10\3"+
    "\1\176\1\3\1\0\1\3\1\0\11\3\46\0\1\177"+
    "\6\0\1\3\1\43\11\0\1\44\7\0\12\3\1\0"+
    "\1\3\1\0\4\3\1\200\4\3\2\0\1\3\1\43"+
    "\11\0\1\44\7\0\12\3\1\0\1\3\1\0\6\3"+
    "\1\201\2\3\2\0\1\3\1\43\11\0\1\44\7\0"+
    "\4\3\1\202\5\3\1\0\1\3\1\0\11\3\2\0"+
    "\1\3\1\43\11\0\1\44\7\0\1\3\1\203\10\3"+
    "\1\0\1\3\1\0\11\3\2\0\1\3\1\43\11\0"+
    "\1\44\7\0\4\3\1\204\5\3\1\0\1\3\1\0"+
    "\11\3\34\0\1\205\20\0\1\3\1\43\11\0\1\44"+
    "\7\0\7\3\1\206\2\3\1\0\1\3\1\0\11\3"+
    "\2\0\1\3\1\43\11\0\1\44\7\0\11\3\1\207"+
    "\1\0\1\3\1\0\11\3\2\0\1\3\1\43\11\0"+
    "\1\44\7\0\11\3\1\210\1\0\1\3\1\0\11\3"+
    "\31\0\1\211\23\0\1\3\1\43\11\0\1\44\7\0"+
    "\4\3\1\212\5\3\1\0\1\3\1\0\11\3\44\0"+
    "\1\213\10\0\1\3\1\43\11\0\1\44\7\0\12\3"+
    "\1\0\1\3\1\0\2\3\1\214\6\3\2\0\1\3"+
    "\1\43\11\0\1\44\7\0\4\3\1\215\5\3\1\0"+
    "\1\3\1\0\11\3\35\0\1\216\17\0\1\3\1\43"+
    "\11\0\1\44\7\0\10\3\1\217\1\3\1\0\1\3"+
    "\1\0\11\3\31\0\1\220\23\0\1\3\1\43\11\0"+
    "\1\44\7\0\4\3\1\221\5\3\1\0\1\3\1\0"+
    "\11\3\2\0\1\3\1\43\11\0\1\44\7\0\12\3"+
    "\1\0\1\3\1\0\10\3\1\222\2\0\1\3\1\43"+
    "\11\0\1\44\7\0\5\3\1\223\4\3\1\0\1\3"+
    "\1\0\11\3\2\0\1\3\1\43\11\0\1\44\7\0"+
    "\10\3\1\224\1\3\1\0\1\3\1\0\11\3\2\0"+
    "\1\3\1\43\11\0\1\44\7\0\12\3\1\225\1\226"+
    "\1\0\11\3\31\0\1\227\23\0\1\3\1\43\11\0"+
    "\1\44\7\0\4\3\1\230\5\3\1\0\1\3\1\0"+
    "\11\3\2\0\1\3\1\43\11\0\1\44\7\0\12\3"+
    "\1\0\1\3\1\0\6\3\1\231\2\3\2\0\1\3"+
    "\1\43\11\0\1\44\7\0\6\3\1\232\3\3\1\0"+
    "\1\3\1\0\11\3\27\0\1\233\25\0\1\3\1\43"+
    "\11\0\1\44\7\0\2\3\1\234\7\3\1\0\1\3"+
    "\1\0\11\3\26\0\1\235\26\0\1\3\1\43\11\0"+
    "\1\44\7\0\1\3\1\236\10\3\1\0\1\3\1\0"+
    "\11\3\2\0\1\3\1\43\11\0\1\44\7\0\10\3"+
    "\1\237\1\3\1\0\1\3\1\0\11\3\2\0\1\3"+
    "\1\43\11\0\1\44\7\0\1\3\1\240\10\3\1\0"+
    "\1\3\1\0\11\3\35\0\1\241\17\0\1\3\1\43"+
    "\11\0\1\44\7\0\10\3\1\242\1\3\1\0\1\3"+
    "\1\0\11\3\2\0\1\3\1\43\11\0\1\44\7\0"+
    "\4\3\1\243\5\3\1\0\1\3\1\0\11\3\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4601];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\1\1\1\11\3\1\1\11"+
    "\1\1\3\11\1\1\2\11\17\1\1\11\1\1\2\0"+
    "\2\11\1\0\1\11\1\0\1\11\20\1\1\11\1\1"+
    "\1\11\13\1\1\0\10\1\1\0\1\1\1\0\7\1"+
    "\1\0\6\1\1\0\7\1\1\11\1\0\2\1\1\11"+
    "\3\1\1\0\3\1\1\0\2\1\1\0\3\1\1\0"+
    "\5\1\1\11\3\1\1\11\1\1\1\0\2\1\1\11"+
    "\1\1\1\11\4\1\1\0\1\1\1\0\3\1\1\0"+
    "\1\1\1\11\3\1\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[163];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 178) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { System.out.println("Caracter ilegal: " + yytext());
          }
        case 48: break;
        case 2: 
          { return new Symbol(sym.ID, yycolumn, yyline, yytext());
          }
        case 49: break;
        case 3: 
          { return new Symbol(sym.NUM, yycolumn, yyline, yytext());
          }
        case 50: break;
        case 4: 
          { 
          }
        case 51: break;
        case 5: 
          { return new Symbol(sym.OPDEC, yycolumn, yyline, yytext());
          }
        case 52: break;
        case 6: 
          { return new Symbol(sym.OPREL, yycolumn, yyline, yytext());
          }
        case 53: break;
        case 7: 
          { return new Symbol(sym.OPMULT, yycolumn, yyline, yytext());
          }
        case 54: break;
        case 8: 
          { return new Symbol(sym.OPSUM, yycolumn, yyline, yytext());
          }
        case 55: break;
        case 9: 
          { return new Symbol(sym.PARIZQ, yycolumn, yyline, yytext());
          }
        case 56: break;
        case 10: 
          { return new Symbol(sym.PARDER, yycolumn, yyline, yytext());
          }
        case 57: break;
        case 11: 
          { return new Symbol(sym.PYC, yycolumn, yyline, yytext());
          }
        case 58: break;
        case 12: 
          { return new Symbol(sym.COMA, yycolumn, yyline, yytext());
          }
        case 59: break;
        case 13: 
          { System.out.print(yytext());
          }
        case 60: break;
        case 14: 
          { return new Symbol(sym.OPASG, yycolumn, yyline, yytext());
          }
        case 61: break;
        case 15: 
          { return new Symbol(sym.CAJA, yycolumn, yyline, yytext());
          }
        case 62: break;
        case 16: 
          { return new Symbol(sym.DOSPUNTOS, yycolumn, yyline, yytext());
          }
        case 63: break;
        case 17: 
          { return new Symbol(sym.STR, yycolumn, yyline, yytext());
          }
        case 64: break;
        case 18: 
          { return new Symbol(sym.OR, yycolumn, yyline, yytext());
          }
        case 65: break;
        case 19: 
          { return new Symbol(sym.OF, yycolumn, yyline, yytext());
          }
        case 66: break;
        case 20: 
          { return new Symbol(sym.IF, yycolumn, yyline, yytext());
          }
        case 67: break;
        case 21: 
          { return new Symbol(sym.IN, yycolumn, yyline, yytext());
          }
        case 68: break;
        case 22: 
          { return new Symbol(sym.IS, yycolumn, yyline, yytext());
          }
        case 69: break;
        case 23: 
          { return new Symbol(sym.PUT, yycolumn, yyline, yytext());
          }
        case 70: break;
        case 24: 
          { return new Symbol(sym.OUT, yycolumn, yyline, yytext());
          }
        case 71: break;
        case 25: 
          { return new Symbol(sym.END, yycolumn, yyline, yytext());
          }
        case 72: break;
        case 26: 
          { return new Symbol(sym.FOR, yycolumn, yyline, yytext());
          }
        case 73: break;
        case 27: 
          { return new Symbol(sym.GET, yycolumn, yyline, yytext());
          }
        case 74: break;
        case 28: 
          { return new Symbol(sym.AND, yycolumn, yyline, yytext());
          }
        case 75: break;
        case 29: 
          { return new Symbol(sym.XOR, yycolumn, yyline, yytext());
          }
        case 76: break;
        case 30: 
          { return new Symbol(sym.ELSE, yycolumn, yyline, yytext());
          }
        case 77: break;
        case 31: 
          { return new Symbol(sym.EXIT, yycolumn, yyline, yytext());
          }
        case 78: break;
        case 32: 
          { return new Symbol(sym.TRUE, yycolumn, yyline, yytext());
          }
        case 79: break;
        case 33: 
          { return new Symbol(sym.THEN, yycolumn, yyline, yytext());
          }
        case 80: break;
        case 34: 
          { return new Symbol(sym.LOOP, yycolumn, yyline, yytext());
          }
        case 81: break;
        case 35: 
          { return new Symbol(sym.WHEN, yycolumn, yyline, yytext());
          }
        case 82: break;
        case 36: 
          { return new Symbol(sym.RANGE, yycolumn, yyline, yytext());
          }
        case 83: break;
        case 37: 
          { return new Symbol(sym.ELSIF, yycolumn, yyline, yytext());
          }
        case 84: break;
        case 38: 
          { return new Symbol(sym.FLOAT, yycolumn, yyline, yytext());
          }
        case 85: break;
        case 39: 
          { return new Symbol(sym.FALSE, yycolumn, yyline, yytext());
          }
        case 86: break;
        case 40: 
          { return new Symbol(sym.BEGIN, yycolumn, yyline, yytext());
          }
        case 87: break;
        case 41: 
          { return new Symbol(sym.WHILE, yycolumn, yyline, yytext());
          }
        case 88: break;
        case 42: 
          { return new Symbol(sym.ARRAY, yycolumn, yyline, yytext());
          }
        case 89: break;
        case 43: 
          { return new Symbol(sym.RETURN, yycolumn, yyline, yytext());
          }
        case 90: break;
        case 44: 
          { return new Symbol(sym.INT, yycolumn, yyline, yytext());
          }
        case 91: break;
        case 45: 
          { return new Symbol(sym.BOOLEAN, yycolumn, yyline, yytext());
          }
        case 92: break;
        case 46: 
          { return new Symbol(sym.FUNCTION, yycolumn, yyline, yytext());
          }
        case 93: break;
        case 47: 
          { return new Symbol(sym.PROCEDURE, yycolumn, yyline, yytext());
          }
        case 94: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	return new Symbol(sym.EOF,new String("Fin del archivo"));
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
