
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 10 21:58:22 CST 2014
//----------------------------------------------------

package kickassdb;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 12;
  public static final int FROM = 11;
  public static final int AND = 13;
  public static final int KEY = 5;
  public static final int ASTERISK = 21;
  public static final int SEMICOLON = 19;
  public static final int SELECT = 10;
  public static final int OR = 14;
  public static final int INT = 15;
  public static final int ID = 23;
  public static final int TABLE = 3;
  public static final int NUM = 24;
  public static final int COMA = 20;
  public static final int VARCHAR = 16;
  public static final int CREATE = 2;
  public static final int INSERT = 6;
  public static final int EOF = 0;
  public static final int VALUES = 8;
  public static final int PARRIGHT = 18;
  public static final int error = 1;
  public static final int PRIMARY = 4;
  public static final int STR = 25;
  public static final int PARLEFT = 17;
  public static final int OPREL = 22;
  public static final int NULL = 9;
  public static final int INTO = 7;
}

