
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 11 15:37:37 CST 2014
//----------------------------------------------------

package kickassdb;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int KEY = 5;
  public static final int SEMICOLON = 16;
  public static final int INT = 9;
  public static final int ID = 18;
  public static final int TABLE = 3;
  public static final int NUM = 19;
  public static final int OPMULT = 13;
  public static final int COMA = 17;
  public static final int VARCHAR = 10;
  public static final int CREATE = 2;
  public static final int INSERT = 6;
  public static final int EOF = 0;
  public static final int VALUES = 8;
  public static final int PARRIGHT = 15;
  public static final int error = 1;
  public static final int PRIMARY = 4;
  public static final int STR = 20;
  public static final int PARLEFT = 14;
  public static final int OPSUM = 12;
  public static final int OPREL = 11;
  public static final int INTO = 7;
}

